//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCompany()
        {
            this.tblCompanyLicenseDetails = new HashSet<tblCompanyLicenseDetail>();
        }
    
        public int CompanyId { get; set; }
        public int CompanyTypeId { get; set; }
        public string CompanyName { get; set; }
        public string GSTNo { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string PinCode { get; set; }
        public string PANNo { get; set; }
        public string Website { get; set; }
        public string ContactPerson { get; set; }
        public string CINNo { get; set; }
        public Nullable<System.DateTime> FYStartDate { get; set; }
        public Nullable<System.DateTime> BookStartDate { get; set; }
        public string Branch { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string MobileNo { get; set; }
    
        public virtual tblCompanyType tblCompanyType { get; set; }
        public virtual tblCountry tblCountry { get; set; }
        public virtual tblState tblState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCompanyLicenseDetail> tblCompanyLicenseDetails { get; set; }
    }
}
